---
# 1. Installation
- name: "Installation Apache"
  ansible.builtin.apt:
    name: "{{ apache_package_name }}"
    state: present
    update_cache: true
  tags:
    - install

# 2. Activation des modules nécessaires
- name: "Activation des modules de Proxy et Load Balancing"
  community.general.apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - proxy
    - proxy_http
    - proxy_balancer
    - lbmethod_byrequests
  notify: "Restart apache"
  tags:
    - config

# 3. Configuration via Template
- name: "Configuration Apache (Dynamic ProxyPass)"
  ansible.builtin.template:
    src: apache2.conf.j2
    dest: /etc/apache2/apache2.conf
    owner: root
    group: root
    mode: '0644'
  notify: "Restart apache"
  tags:
    - config

# 4. Suppression des fichiers polluants
- name: "Supprimer les configurations par défaut"
  ansible.builtin.file:
    path: "/etc/apache2/{{ item }}"
    state: absent
  loop:
    - "sites-enabled/000-default.conf"
    - "conf-enabled/serve-cgi-bin.conf"
  notify: "Restart apache"
  tags:
    - config

# 5. Préparation de l'environnement Web
- name: "S'assurer que le répertoire web existe"
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    mode: '0755'
    owner: www-data
    group: www-data
  tags:
    - config

# 6. Vérification avant redémarrage
- name: "Vérification de la syntaxe Apache"
  ansible.builtin.command: apache2ctl configtest
  changed_when: false
  tags:
    - config

# 7. Application immédiate des handlers
- name: "Appliquer les changements"
  ansible.builtin.meta: flush_handlers

# 8. Démarrage du service
- name: "Démarrage et activation du Service"
  ansible.builtin.service:
    name: "{{ apache_service_name }}"
    state: started
    enabled: true
  tags:
    - service

# 9. Validation du routage
- name: "Vérification : Le WAF répond (200 ou 503)"
  ansible.builtin.uri:
    url: "http://localhost:{{ apache_listen_port | default('80') }}"
    status_code: [200, 503]
  register: apache_web_test
  until: apache_web_test.status in [200, 503]
  retries: 5
  delay: 3
  changed_when: false
  tags:
    - test
