---
- name: "DESTROY : Suppression complète des conteneurs du Lab"
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    instances: ["waf-01", "web-01", "web-02", "app-01", "app-02", "db-01"]

  tasks:
    - name: "Suppression forcée des conteneurs Incus"
      community.general.incus_container:
        name: "{{ item }}"
        state: absent
      loop: "{{ instances }}"
