---
- name: "Installation de Zabbix Agent"
  ansible.builtin.apt:
    name: zabbix-agent
    state: present
    update_cache: true
  tags:
    - zabbix
    - install

- name: "Configuration de Zabbix Agent"
  ansible.builtin.template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: '0644'
  notify: "Restart zabbix-agent"
  tags:
    - zabbix
    - config

- name: "Démarrage et activation du service Zabbix Agent"
  ansible.builtin.systemd_service:
    name: zabbix-agent
    state: started
    enabled: true
  tags:
    - zabbix
    - service
