---
# 1. Installation
- name: "Installation de HAProxy"
  ansible.builtin.apt:
    name: haproxy
    state: present
    update_cache: true
  become: true
  tags:
    - install

# 2. Configuration
- name: "Configuration de HAProxy"
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: "Restart haproxy"
  tags:
    - config

# 3. Démarrage du service
- name: "Démarrage de HAProxy"
  ansible.builtin.systemd_service:
    name: haproxy
    state: started
    enabled: true
  become: true
  tags:
    - service
